painel/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


urlpatterns = [
    path('auth/login', render,
         {'template_name': 'auth/login.html'}, name='auth/login'),
    path('auth/logoff', render,
         {'template_name': 'auth/login.html'}, name='auth/logoff'),
    path('relatorios/', render,
         {'template_name': 'auth/login.html'}, name='relatorios/'),
]

website/urls.py
from django.urls import path, include
from django.shortcuts import render, redirect
from django.urls import reverse

from website.views.produtos import produto, procurar
from website.views.auth import urlpatterns as auth_patterns
from website.views.carrinho import urlpatterns as carrinho_patterns
from website.views.produtos import urlpatterns as produtos_patterns
from website.views.user import urlpatterns as user_patterns

from website.views import render_index, render_sobrenos
urlpatterns = [
    path('', render_index, name='home'),
    path('/sobre-nos/', render_sobrenos, name='sobre-nos'),
] + auth_patterns + produtos_patterns + carrinho_patterns + user_patterns

website/forms/produtos.py
from django import forms
from django.forms import HiddenInput, formset_factory
from django.db.models import Max, Q
from django.db.models.functions import Length

from manager.models.produtos import Categoria, PedidoDesconto, Produto, Tag
from django.db import models
from django.utils import timezone

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Div, HTML


class FiltroProdutos (forms.Form):
    q = forms.CharField(label='Pesquisar', required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Pesquisar', 'class': 'form-control'}))
    # Categorias irá ser por ID
    categorias = forms.MultipleChoiceField(
        required=False, widget=forms.CheckboxSelectMultiple)
    # Tags irá ser por ID/Nome
    tags = forms.MultipleChoiceField(
        required=False, widget=forms.CheckboxSelectMultiple)
    preco_min = forms.DecimalField(
        required=False, min_value=0, step_size=0.01, widget=forms.HiddenInput())
    preco_max = forms.DecimalField(
        required=False, min_value=0, step_size=0.01, widget=forms.HiddenInput())

    order_by = forms.ChoiceField(label='Ordernar por', choices=(
        ('nome', 'Nome'),
        ('preco', 'Preço'),
        ('data_lancamento', 'Lançamento'),
    ), required=False)
    order = forms.ChoiceField(label='Ordem', choices=(
        ('desc', 'Maior para menor'),
        ('asc', 'Menor para maior'),
    ), required=False)

    pagina = forms.IntegerField(required=False, min_value=1)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['categorias'].choices = [
            (c.id, c.nome) for c in Categoria.objects.filter(ativo=True, produto__isnull=False).distinct().order_by(Length('nome'))]
        self.fields['tags'].choices = [(t.id, t.nome)
                                       for t in Tag.objects.filter(ativo=True, produto__isnull=False).distinct().order_by(Length('nome'))]
        self.fields['q'].label = False

        max = Produto.objects.all().aggregate(Max('preco'))['preco__max'] or 0
        max = (max // 10 + 1) * 10

        step_calced = max / 10

        self.fields['preco_min'].widget.attrs['max'] = max
        self.fields['preco_min'].widget.attrs['step'] = step_calced
        self.fields['preco_max'].widget.attrs['max'] = max
        self.fields['preco_max'].widget.attrs['step'] = step_calced
        self.fields['preco_max'].initial = max
        self.fields['preco_min'].initial = 0

        self.helper = FormHelper()
        self.helper.form_method = 'GET'
        self.helper.field_class = 'input-group input-group-sm'
        self.helper.layout = Layout(
            Fieldset(
                'Pesquisa',
                'categorias',
                'tags',
                Div(HTML('<label class="mb-2">Preço</label>'), Div(id='preco_slide'),
                    'preco_min', 'preco_max'),
                'order_by',
                'order',
                css_class='d-flex flex-column gap-1'
            ),
            Submit('submit', 'Pesquisar'),
        )

    def clean(self):
        cleaned_data = super().clean()
        preco_min = cleaned_data.get('preco_min')
        preco_max = cleaned_data.get('preco_max')

        # Raise on preco_min field
        if preco_min and preco_max and preco_min > preco_max:
            raise forms.ValidationError(
                'O preço mínimo não pode ser maior que o preço máximo.')

        # Raise on preco_max field
        if preco_max and preco_min and preco_max < preco_min:
            raise forms.ValidationError(
                'O preço máximo não pode ser menor que o preço mínimo.')

        return cleaned_data

    def search(self):
        produtos = Produto.objects.all()

        q = self.cleaned_data['q']
        if q:
            produtos = produtos.filter(nome__icontains=q)

        categorias = self.cleaned_data['categorias']
        if categorias:
            produtos = produtos.filter(categorias__id__in=categorias)

        tags = self.cleaned_data['tags']
        if tags:
            produtos = produtos.filter(tags__id__in=tags)

        preco_min = self.cleaned_data['preco_min']
        if preco_min:
            produtos = produtos.filter(preco__gte=preco_min)

        preco_max = self.cleaned_data['preco_max']
        if preco_max:
            produtos = produtos.filter(preco__lte=preco_max)

        order_by = self.cleaned_data['order_by'] or 'nome'
        order_prefix = '-' if self.cleaned_data['order'] == 'desc' else ''

        # # Vai pegar o desconto aplicado, proximo aos produtos, tags e categorias

        # produtos = produtos.annotate(
        #     desconto=PedidoDesconto.objects.filter(
        #         retorno='P',
        #         ativo=True
        #     ).filter(
        #         Q(inicio__lte=timezone.now()) | Q(inicio__isnull=True),
        #         Q(fim__gte=timezone.now()) | Q(fim__isnull=True)
        #     ).filter(
        #         Q(categorias__in=models.OuterRef('categorias')) |
        #         Q(tags__in=models.OuterRef('tags')) |
        #         Q(produtos__in=models.OuterRef('pk'))
        #     ).annotate(
        #         calculado=models.Case(
        #             models.When(tipo='P', then=models.F(
        #                 'desconto') * models.OuterRef('preco') / 100),
        #             models.When(tipo='V', then=models.F('desconto')),
        #             default=0,
        #             output_field=models.DecimalField()
        #         )
        #     ).order_by('-calculado').values('calculado')[:1]
        # ).annotate(preco_liquido2=models.F('preco') - models.F('desconto'))

        # # Se for ordenar por preço, ordena pelo desconto

        # if order_by == 'preco':
        #     order_by = 'preco_liquido2'

        # import json

        # produtos = produtos.order_by(f'{order_prefix}{order_by}')
        # print(json.dumps([(item.nome, float(item.desconto or 0), float(item.preco))
        #       for item in produtos.distinct()]))
        # print(produtos.query)

        return produtos.distinct()

website/forms/user.py
from django import forms

from manager.models.usuario import Usuario


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'imagem']

website/views/carrinho.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.urls import path
from django.db import transaction
from manager.models.produtos import CarrinhoItem, Pedido, PedidoItem
from website.forms.carrinho import CarrinhoAction, CarrinhoFinalizar
from website.utils import build_meta

from django.contrib.auth.decorators import login_required


@require_http_methods(['GET'])
@login_required
def carrinho(req):
    items = CarrinhoItem.objects.filter(user=req.user)
    total, preco_bruto, preco_desconto = 0, 0, 0
    qntd = 0

    for item in items:
        total += item.produto.preco_liquido()
        preco_bruto += item.produto.preco
        preco_desconto += item.produto.desconto_preco()

    return render(req, 'carrinho.html', {
        'page': build_meta('Carrinho', 'Carrinho de compras'),
        'itens': items,
        'info': {
            'total': {
                'bruto': preco_bruto,
                'desconto': preco_desconto,
                'liquido': total
            },
            'quantidade': qntd,
            'items': len(items),
        }
    })


@require_http_methods(['POST'])
@login_required
def finalizar(req):
    carrinho = CarrinhoFinalizar(req.POST)
    if not carrinho.is_valid():
        return JsonResponse(carrinho.errors, status=400)
    try:
        with transaction.atomic():
            items = CarrinhoItem.objects.filter(user=req.user)
            cupom = carrinho.cleaned_data['cupom']

            pedido = Pedido(
                user=req.user
            )

            for item in items:
                produto = item.produto
                if produto.estoque < item.quantidade:
                    return JsonResponse({'status': 'error', 'message': f'{produto.nome} só tem {produto.estoque} unidades disponíveis, favor remontar seu carrinho.'}, status=400)

                pedido_item = PedidoItem.objects.create(
                    produto=item.produto,
                    quantidade=item.quantidade,
                    desconto=item.produto.desconto(),
                    cupom=cupom if cupom and cupom.aplicavel(
                        item.produto) else None
                )
                pedido_item.save()
                pedido.itens.add(pedido_item)

            items.delete()
            pedido.save()

            return JsonResponse({'status': 'success'})
    except:
        return JsonResponse({'status': 'error', 'message': 'Erro ao finalizar compra'}, status=400)


@require_http_methods(['POST'])
@login_required
def add_carrinho(req):
    carrinho = CarrinhoAction(json.loads(req.body))
    if not carrinho.is_valid():
        return JsonResponse(carrinho.errors, status=400)
    return JsonResponse(carrinho.save(req.user))


@require_http_methods(['POST'])
@login_required
def remover_carrinho(req):
    carrinho = CarrinhoAction(json.loads(req.body))
    if not carrinho.is_valid():
        return JsonResponse(carrinho.errors, status=400)

    return JsonResponse(carrinho.delete(req.user))


@require_http_methods(['POST'])
@login_required
def clear_carrinho(req):
    CarrinhoItem.objects.filter(user=req.user).delete()
    return JsonResponse({
        'status': 'success',
    })


urlpatterns = [
    path('carrinho/', carrinho, name='carrinho'),
    path('api/carrinho/finalizar', finalizar, name='carrinho/finalizar'),
    path('api/carrinho/add', add_carrinho, name='carrinho/add'),
    path('api/carrinho/rem', remover_carrinho, name='carrinho/remover'),
    path('api/carrinho/clear', clear_carrinho, name='carrinho/limpar'),
]

website/views/error.py
from django.shortcuts import render
from website.utils import build_meta


def not_found(req, exception=None):
    return render(req, 'website:error/generic.html', {
        'page': build_meta('404', 'Página não encontrada'),
        'error': '404',
        'message': 'Página não encontrada',
        'exception': exception or 'Erro desconhecido'
    })


def server_error(req, exception=None):
    return render(req, 'error/generic.html', {
        'page': build_meta('500', 'Erro interno'),
        'error': '500',
        'message': 'Erro interno',
        'exception': exception or 'Erro desconhecido'
    })


def permission_denied(req, exception=None):
    return render(req, 'error/generic.html', {
        'page': build_meta('403', 'Acesso negado'),
        'error': '403',
        'message': 'Acesso negado',
        'exception': exception or 'Erro desconhecido'
    })


def bad_request(req, exception=None):
    return render(req, 'error/generic.html', {
        'page': build_meta('400', 'Requisição inválida'),
        'error': '400',
        'message': 'Requisição inválida',
        'exception': exception or 'Erro desconhecido'
    })


def csrf_failure(req, reason=''):
    return render(req, 'error/generic.html', {
        'page': build_meta('403', 'Acesso negado'),
        'error': '403',
        'message': 'Acesso negado\n\n' + reason
    })

website/views/produtos.py
from django.urls import path, reverse
from django.utils import timezone
from django.shortcuts import redirect, render
from django.http import HttpRequest, HttpResponse

from manager.models import Produto
from manager.models.produtos import CarrinhoItem, Categoria
from website.forms.produtos import FiltroProdutos
from website.utils import build_meta, redirect_current, redirect_to

from django.db.models import Max
from django.core.paginator import Paginator
from django.contrib.humanize.templatetags.humanize import intcomma

import json


def produto(req: HttpRequest, produto_id: int, raw_slug: str = '') -> HttpResponse:
    try:
        produto = Produto.objects.get(ativo=True, id=produto_id)

        if produto.slug != raw_slug:
            return redirect_current(
                req, _args={"produto_id": produto_id, "raw_slug": produto.slug})

        if produto.data_lancamento and produto.data_lancamento > timezone.now() and not (req.user and req.user.is_staff):
            return redirect_to(req, 'inicio')

        carrinho = CarrinhoItem.objects.filter(
            user=req.user, produto=produto).first() if req.user.is_authenticated else None
        if carrinho:
            carrinho = carrinho.quantidade
        else:
            carrinho = 0

        return render(req, 'produto.html', {
            'page': {
                'title': f"{produto.nome} - ePlay Commerce",
                'description': produto.descricao,
                'keywords': [*produto.tags.all().values_list('nome', flat=True), *produto.categorias.all().values_list('nome', flat=True)],
                'author': 'Dalton Lins, Jussara Kelly - Equipe ePlay Commerce'
            },
            'produto': produto,
            'carrinho': carrinho,
            'produto_meta': json.dumps({
                "@context": "https://schema.org",
                "@type": "Product",
                'sku': produto.id,
                'name': produto.nome,
                'description': produto.descricao,
                'imagem': f"{req.scheme}://{req.get_host()}{produto.thumbnail.url}",
                "offers": {
                    "@type": "Offer",
                    "availability":  "https://schema.org/InStock" if produto.estoque > 0 else "https://schema.org/OutOfStock",
                    "price": intcomma(produto.preco),
                    "priceCurrency": "BRL",
                    "url": f"{req.scheme}://{req.get_host()}{reverse('produto', kwargs={'produto_id': produto.id})}"
                }
            })
        })
    except Produto.DoesNotExist:
        return redirect('/')


def procurar(req: HttpRequest) -> HttpResponse:
    form = FiltroProdutos(req.GET or None)
    if form.is_valid():
        produtos = form.search()
    else:
        produtos = Produto.objects.all()

    produtos = produtos if req.user and req.user.is_staff else produtos.filter()
    paginacao = Paginator(produtos, 16)

    try:
        paginacao = paginacao.page(form.cleaned_data.get('pagina', 1))
    except:
        paginacao = paginacao.page(1)

    return render(req, 'produtos.html', {
        "page": build_meta('Pesquisa de Produtos'),
        "form": form,
        "paginacao": paginacao
    })


def categorias(req):
    return render(req, 'categorias.html', {
        'page': build_meta('Categorias'),
        'categorias': Categoria.objects.filter(ativo=True, produto__isnull=False).distinct()
    })


urlpatterns = [
    path('produto/', procurar, name='produtos'),
    path('produto/<int:produto_id>-<slug:raw_slug>', produto, name='produto'),
    path('produto/<int:produto_id>', produto, name='produto'),
    path('categorias/', categorias, name='categorias')
]

website/views/user.py
from django.shortcuts import redirect, render
from django.urls import path
from eplay_commerce.settings import MEDIA_URL
from manager.models.produtos import Pedido
from manager.models.usuario import Usuario

from website.forms.user import SettingsForm
from website.utils import build_meta

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


@require_http_methods(['GET', 'POST'])
@login_required
def settings(req):
    if req.method == 'POST':
        form = SettingsForm(req.POST, req.FILES, instance=req.user)
        if form.is_valid():
            form.save()
            return redirect('user/settings')
    else:
        form = SettingsForm(instance=req.user)

    return render(req, 'user/config.html', {
        'page': build_meta('Configurações'),
        'form': form
    })


@require_http_methods(['GET'])
@login_required
def orders(req):
    pedidos = Pedido.objects.filter(user=req.user)
    return render(req, 'pedidos.html', {
        'page': build_meta('Pedidos', 'Pedidos realizados'),
        'pedidos': pedidos,
    })


urlpatterns = [
    path('user/configuracao', settings, name='user/settings'),
    path('user/pedidos', orders, name='user/orders')
]

website/templates/carrinho.html
{% extends "layout/index.html" %}
{% load website_tags %}
{% load humanize %}
{% load static %}
{% block head %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.8/dist/sweetalert2.min.css"
          integrity="sha256-sWZjHQiY9fvheUAOoxrszw9Wphl3zqfVaz1kZKEvot8="
          crossorigin="anonymus"/>
    
{% endblock head %}
<!--  Listagem os itens do pedido, com um header contendo as informações de total, quantidade, e produtos -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Meu Carrinho</h1>
                <hr/>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Produto</th>
                                    <th>Quantidade</th>
                                    <th>Preço</th>
                                    <th>Desconto</th>
                                    <th>Total</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in itens.all %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'produto' produto_id=item.produto.id %}">{{ item.produto.nome }}</a>
                                        </td>
                                        <td>{{ item.quantidade }}</td>
                                        <td>R$ {{ item.preco_bruto|floatformat:2|intcomma }}</td>
                                        <td>R$ {{ item.preco_desconto|floatformat:2|intcomma }}</td>
                                        <td>R$ {{ item.total|floatformat:2|intcomma }}</td>
                                        <td>
                                            <button class="btn btn-danger btn-sm remover-produto"
                                                    data-id="{{ item.produto.id }}"
                                                    data-redirect="true">
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     xmlns:xlink="http://www.w3.org/1999/xlink"
                                                     width="20px"
                                                     height="20px"
                                                     viewBox="0 0 20 20"
                                                     version="1.1">
                                                    <path d="M 5.1875 15.6875 L 4.3125 14.8125 L 9.125 10 L 4.3125 5.1875 L 5.1875 4.3125 L 10 9.125 L 14.8125 4.3125 L 15.6875 5.1875 L 10.875 10 L 15.6875 14.8125 L 14.8125 15.6875 L 10 10.875 Z M 5.1875 15.6875 "/>
                                                </svg>
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="2" class="text-right">Total</td>
                                    <td>R$ {{ info.total.bruto|floatformat:2|intcomma }}</td>
                                    <td>R$ {{ info.total.desconto|floatformat:2|intcomma }}</td>
                                    <td>R$ {{ info.total.liquido|floatformat:2|intcomma }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <a id="finalizar" class="btn btn-primary">Finalizar Compra</a>
                </div>
            </div>
        </div>
    </div>
    <form id="csfr">
        {% csrf_token %}
    </form>
{% endblock content %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.8/dist/sweetalert2.min.js"
            integrity="sha256-Hwfn4rHzN55PApkU+MW1HDu4MjBqBMtKEf6YRi2of2Q="
            crossorigin="anonymous"></script>
    <script src="{% static 'js/cart.js' %}"></script>
{% endblock scripts %}

website/templates/categorias.html
{% extends "layout/index.html" %}
{% load website_tags %}
<!--  Listagem de categorias -->
{% block content %}
    <div class="container rounded p-3">
        <div class="display-3">
            <h1>Listagem de Categorias</h1>
        </div>
        <div class="d-flex flex-wrap text-white bg-dark border border-little p-2 gap-2">
            {% for categoria in categorias %}
                <a href="{% redirect_to 'produtos' categorias=categoria.id %}"
                   class="text-white bg-deepdark text-decoration-none px-3 py-1 bg-dark border border-little rounded">{{ categoria.nome }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

website/templates/produtos.html
{% extends "layout/index.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}
{% load website_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/produtos.css' %}" />
    <link rel="stylesheet"
          href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/themes/smoothness/jquery-ui.css"/>
{% endblock head %}
{% block title %}
    Produtos - ePlay Commerce
{% endblock title %}
{% block mainTags %}
    class="container-fluid d-flex flex-column flex-sm-row"{% endblock mainTags %}
    {% block content %}
        <div class="filter">
            <form id="filtro"
                  method="post"
                  class="form bg-dark text-white p-3 rounded position-sticky">
                {% crispy form %}
            </form>
        </div>
        <div class="products">
            <div class="search bg-dark rounded">
                <div>
                    Total de produtos: {{ paginacao.paginator.count }} ({{ paginacao.number }}/{{ paginacao.paginator.num_pages }} páginas)
                </div>
                <form id="pesquisar"
                      method="post"
                      class="form bg-dark text-white p-3 rounded">
                    <div class="input-group">{{ form.q }}</div>
                </form>
            </div>
            <div class="list">
                {% for produto in paginacao %}
                    <a href="{% url 'produto' produto_id=produto.id %}" class="produto">
                        <div class="body">
                            <div class="imagem">
                                <div>
                                    <img src="{{ produto.thumbnail.url }}" alt="{{ produto.nome }}" />
                                </div>
                            </div>
                            <div class="info">
                                <p class="nome">{{ produto.nome }}</p>
                                <p class="slogan text-break">{{ produto.slogan }}</p>
                            </div>
                        </div>
                        <div class="preco">
                            {% if produto.desconto %}
                                <p class="desconto bage text-white">{{ produto.porcentagem|floatformat:0 }}%</p>
                                <p class="preco-antigo text-white">R$ {{ produto.preco|floatformat:2|intcomma }}</p>
                            {% endif %}
                            {% if produto.preco_liquido == 0 %}
                                <p class="preco-novo text-white">Grátis</p>
                            {% else %}
                                <p class="preco-novo text-white">R$ {{ produto.preco_liquido|floatformat:2|intcomma }}</p>
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                <nav aria-label="Navegação de Pagina">
                    <ul class="pagination">
                        <li class="page-item{% if not paginacao.has_previous %} disabled{% endif %}">
                            <a class="page-link"
                               {% if paginacao.has_previous %}href="{% redirect_current pagina=paginacao.previous_page_number %}" {% endif %}>Voltar</a>
                        </li>
                        {% for i in paginacao.paginator.page_range %}
                            <li class="page-item">
                                {% if paginacao.number == i %}
                                    <a class="page-link disabled">{{ i }}</a>
                                {% else %}
                                    <a class="page-link" href="{% redirect_current pagina=i %}">{{ i }}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                        <li class="page-item{% if not paginacao.has_next %} disabled{% endif %}">
                            <a class="page-link"
                               {% if paginacao.has_next %}href="{% redirect_current pagina=paginacao.next_page_number %}" {% endif %}>Proxímo</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--- Retorna as informações do produto que vai ser visto -->
    {% endblock content %}
    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
        <script>
    $(() => {
        const min = $("#id_preco_min");
        const max = $("#id_preco_max");

        $("#preco_slide").slider({
            range: true,
            min: 0,
            step: max.attr('step'),
            max: max.attr('max'),
            values: [parseFloat(min.val()), parseFloat(max.val())],
            slide: function (event, ui) {
                min.val(ui.values[0]);
                max.val(ui.values[1]);
            }
        });

        const form = $("#filtro, #pesquisar");

        form.submit(function (e) {
            e.preventDefault();

            const data = [...new FormData(window.document.getElementById("filtro")).entries(), ...new FormData(window.document.getElementById("pesquisar")).entries()];

            const url = new URL(window.location.href);
            url.search = data.reduce((params, [key, value]) => {
                params.append(key, value);
                return params;
            }, new URLSearchParams()).toString();
            window.location = url;
        });
    });
        </script>
    {% endblock scripts %}

website/templates/sobre-nos.html
{% extends "layout/index.html" %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/sobre-nos.css' %}" />
{% endblock %} {% block content %}
<div class="container p-2 gap-4 d-flex flex-column">
  <div class="row bg-dark border border-little p-3 rounded d-flex flex-column gap-3">
    <div>
      <h1>Sobre o site</h1>
      <p>O site foi criado baseado nos e-commerce de jogos, com intuito de facilitar a venda de jogos e derivados do mundo virtual dos games.</p>
    </div>
    <div class="col border border-little p-3 bg-deepdark rounded">
      <h2>Como funciona?</h2>
      <p>O intuito de tudo é facilitar a venda para os Gamers centralizando tudo do mundo dos games para um e-commerce de jogos.</p>
      <p>Você pode realizar se registrasse e efetuar login para poder comprar os produtos que desejar.</p>
      <p>Você pode realizar a busca de produtos pela categoria, sub-categoria ou tags envolvidas no site.</p>
      <p>Você pode ter uma visualização e agendamentos de produtos que serão lançados no site.</p>
    </div>
  </div>
  <div class="row bg-dark border border-little p-3 rounded d-flex flex-column gap-3">
    <h1>Sobre os criadores</h1>
    <div class="row mx-4">
      <div class="col-md-2">
        <img src="{% static 'img/daltinho.jpg' %}" class="img-fluid rounded-circle" alt="profile" />
      </div>
      <div class="col-md-10">
        <p class="nome py-2 px-3 rounded position-relative left">
          <span class="text-dark position-absolute top-0 start-0 translate-middle badge rounded-pill" style="background-color: #fff; "> Desenvolvedor </span>
          Dalton Lins
        </p>
        <div class="info border border-little bg-deepdark rounded p-4 pb-1">
          <p>
            Atualmente no 4° ano, cursando Técnico Integrado em Informática, pelo IFRN (Campus Pau dos Ferros).<br />
            Sou apaixonado por programação desde os 10 anos, primeira vez com Java no Minecraft.<br />
            Sempre estou busca de novas aventuras para aprender novos conhecimentos e tentar de modos diferentes para expandir minhas fronteiras.
          </p>
        </div>
      </div>
    </div>
    <div class="row mx-4">
      <div class="col-md-10">
        <p class="nome py-2 px-3 rounded position-relative">
          Jussara Kelly
          <span class="text-dark position-absolute top-0 start-100 translate-middle badge rounded-pill" style="background-color: #fff; "> Designer </span>
        </p>
        <div class="info border border-little bg-deepdark rounded p-4 pb-1">
          <p>
            Atualmente no 4° ano, cursando Técnico Integrado em Informática, pelo IFRN (Campus Pau dos Ferros).<br />
            Eu sempre joguei vários jogos e ficava me perguntando como eles eram feitos, acabando por chegar nesse curso.<br />
            Sou apaixonada por LoL e vários outros jogos, talvez não siga na informática mas posso dizer que ela foi essencial na minha vida.
          </p>
        </div>
      </div>
      <div class="col-md-2">
        <img src="{% static 'img/jussara.jpg' %}" class="img-fluid rounded-circle" alt="profile" />
      </div>
    </div>
  </div>
  {% endblock %}
</div>